// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // ␚, reduce: Goroutines
			nil,       // empty
			reduce(2), // tok_enter, reduce: Goroutines
			reduce(2), // goroutine, reduce: Goroutines
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			nil,       // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // ␚
			nil,          // empty
			nil,          // tok_enter
			nil,          // goroutine
			nil,          // tok_int
			nil,          // [
			nil,          // ]:
			nil,          // tok_identifier
			nil,          // ,
			nil,          // minutes
			nil,          // tok_hex
			nil,          // created
			nil,          // by
			nil,          // ...
			nil,          // _
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // ␚, reduce: Start
			nil,       // empty
			shift(4),  // tok_enter
			shift(5),  // goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			nil,       // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // ␚, reduce: Goroutines
			nil,       // empty
			reduce(3), // tok_enter, reduce: Goroutines
			reduce(3), // goroutine, reduce: Goroutines
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			nil,       // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			nil,      // empty
			nil,      // tok_enter
			shift(5), // goroutine
			nil,      // tok_int
			nil,      // [
			nil,      // ]:
			nil,      // tok_identifier
			nil,      // ,
			nil,      // minutes
			nil,      // tok_hex
			nil,      // created
			nil,      // by
			nil,      // ...
			nil,      // _
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			nil,      // empty
			nil,      // tok_enter
			nil,      // goroutine
			shift(7), // tok_int
			nil,      // [
			nil,      // ]:
			nil,      // tok_identifier
			nil,      // ,
			nil,      // minutes
			nil,      // tok_hex
			nil,      // created
			nil,      // by
			nil,      // ...
			nil,      // _
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(4), // ␚, reduce: Goroutines
			nil,       // empty
			reduce(4), // tok_enter, reduce: Goroutines
			reduce(4), // goroutine, reduce: Goroutines
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			nil,       // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			nil,      // empty
			nil,      // tok_enter
			nil,      // goroutine
			nil,      // tok_int
			shift(8), // [
			nil,      // ]:
			nil,      // tok_identifier
			nil,      // ,
			nil,      // minutes
			nil,      // tok_hex
			nil,      // created
			nil,      // by
			nil,      // ...
			nil,      // _
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			shift(10), // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			shift(11), // ]:
			nil,       // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			reduce(6), // ]:, reduce: GStatus
			shift(12), // tok_identifier
			shift(13), // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(14), // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			nil,       // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			reduce(8), // ]:, reduce: GStatus
			nil,       // tok_identifier
			shift(15), // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // tok_enter
			nil,       // goroutine
			shift(16), // tok_int
			nil,       // [
			nil,       // ]:
			nil,       // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(10), // ␚, reduce: GStacks
			nil,        // empty
			reduce(10), // tok_enter, reduce: GStacks
			reduce(10), // goroutine, reduce: GStacks
			nil,        // tok_int
			nil,        // [
			nil,        // ]:
			reduce(10), // tok_identifier, reduce: GStacks
			nil,        // ,
			nil,        // minutes
			nil,        // tok_hex
			reduce(10), // created, reduce: GStacks
			nil,        // by
			nil,        // ...
			nil,        // _
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // tok_enter
			nil,       // goroutine
			shift(18), // tok_int
			nil,       // [
			nil,       // ]:
			nil,       // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			nil,       // tok_identifier
			nil,       // ,
			shift(19), // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // ␚, reduce: Goroutine
			nil,       // empty
			reduce(5), // tok_enter, reduce: Goroutine
			reduce(5), // goroutine, reduce: Goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			shift(20), // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			shift(23), // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			nil,       // tok_identifier
			nil,       // ,
			shift(24), // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			reduce(7), // ]:, reduce: GStatus
			nil,       // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(18), // tok_enter, reduce: GARGS
			nil,        // goroutine
			nil,        // tok_int
			nil,        // [
			nil,        // ]:
			shift(25),  // tok_identifier
			reduce(18), // ,, reduce: GARGS
			nil,        // minutes
			reduce(18), // tok_hex, reduce: GARGS
			nil,        // created
			nil,        // by
			reduce(18), // ..., reduce: GARGS
			reduce(18), // _, reduce: GARGS
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(11), // ␚, reduce: GStacks
			nil,        // empty
			reduce(11), // tok_enter, reduce: GStacks
			reduce(11), // goroutine, reduce: GStacks
			nil,        // tok_int
			nil,        // [
			nil,        // ]:
			reduce(11), // tok_identifier, reduce: GStacks
			nil,        // ,
			nil,        // minutes
			nil,        // tok_hex
			reduce(11), // created, reduce: GStacks
			nil,        // by
			nil,        // ...
			nil,        // _
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			shift(27), // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			nil,       // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			shift(28), // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			reduce(9), // ]:, reduce: GStatus
			nil,       // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			shift(29), // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(30), // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			nil,       // tok_identifier
			shift(31), // ,
			nil,       // minutes
			shift(32), // tok_hex
			nil,       // created
			nil,       // by
			shift(33), // ...
			shift(34), // _
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(35), // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			nil,       // tok_identifier
			nil,       // ,
			nil,       // minutes
			shift(36), // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			shift(37), // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(18), // tok_enter, reduce: GARGS
			nil,        // goroutine
			nil,        // tok_int
			nil,        // [
			nil,        // ]:
			nil,        // tok_identifier
			reduce(18), // ,, reduce: GARGS
			nil,        // minutes
			reduce(18), // tok_hex, reduce: GARGS
			nil,        // created
			nil,        // by
			reduce(18), // ..., reduce: GARGS
			reduce(18), // _, reduce: GARGS
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // tok_enter
			nil,        // goroutine
			nil,        // tok_int
			nil,        // [
			nil,        // ]:
			reduce(14), // tok_identifier, reduce: GFuncCall
			nil,        // ,
			nil,        // minutes
			nil,        // tok_hex
			nil,        // created
			nil,        // by
			nil,        // ...
			nil,        // _
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			nil,       // tok_identifier
			nil,       // ,
			nil,       // minutes
			shift(39), // tok_hex
			nil,       // created
			nil,       // by
			shift(40), // ...
			nil,       // _
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(19), // tok_enter, reduce: GARGS
			nil,        // goroutine
			nil,        // tok_int
			nil,        // [
			nil,        // ]:
			nil,        // tok_identifier
			reduce(19), // ,, reduce: GARGS
			nil,        // minutes
			reduce(19), // tok_hex, reduce: GARGS
			nil,        // created
			nil,        // by
			reduce(19), // ..., reduce: GARGS
			reduce(19), // _, reduce: GARGS
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(21), // tok_enter, reduce: GARGS
			nil,        // goroutine
			nil,        // tok_int
			nil,        // [
			nil,        // ]:
			nil,        // tok_identifier
			reduce(21), // ,, reduce: GARGS
			nil,        // minutes
			reduce(21), // tok_hex, reduce: GARGS
			nil,        // created
			nil,        // by
			reduce(21), // ..., reduce: GARGS
			reduce(21), // _, reduce: GARGS
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(23), // tok_enter, reduce: GARGS
			nil,        // goroutine
			nil,        // tok_int
			nil,        // [
			nil,        // ]:
			nil,        // tok_identifier
			reduce(23), // ,, reduce: GARGS
			nil,        // minutes
			reduce(23), // tok_hex, reduce: GARGS
			nil,        // created
			nil,        // by
			reduce(23), // ..., reduce: GARGS
			reduce(23), // _, reduce: GARGS
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(13), // ␚, reduce: GStack
			nil,        // empty
			reduce(13), // tok_enter, reduce: GStack
			reduce(13), // goroutine, reduce: GStack
			nil,        // tok_int
			nil,        // [
			nil,        // ]:
			reduce(13), // tok_identifier, reduce: GStack
			nil,        // ,
			nil,        // minutes
			nil,        // tok_hex
			reduce(13), // created, reduce: GStack
			nil,        // by
			nil,        // ...
			nil,        // _
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(41), // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			nil,       // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(18), // tok_enter, reduce: GARGS
			nil,        // goroutine
			nil,        // tok_int
			nil,        // [
			nil,        // ]:
			shift(42),  // tok_identifier
			reduce(18), // ,, reduce: GARGS
			nil,        // minutes
			reduce(18), // tok_hex, reduce: GARGS
			nil,        // created
			nil,        // by
			reduce(18), // ..., reduce: GARGS
			reduce(18), // _, reduce: GARGS
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(44), // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			nil,       // tok_identifier
			shift(31), // ,
			nil,       // minutes
			shift(32), // tok_hex
			nil,       // created
			nil,       // by
			shift(33), // ...
			shift(34), // _
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(20), // tok_enter, reduce: GARGS
			nil,        // goroutine
			nil,        // tok_int
			nil,        // [
			nil,        // ]:
			nil,        // tok_identifier
			reduce(20), // ,, reduce: GARGS
			nil,        // minutes
			reduce(20), // tok_hex, reduce: GARGS
			nil,        // created
			nil,        // by
			reduce(20), // ..., reduce: GARGS
			reduce(20), // _, reduce: GARGS
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(22), // tok_enter, reduce: GARGS
			nil,        // goroutine
			nil,        // tok_int
			nil,        // [
			nil,        // ]:
			nil,        // tok_identifier
			reduce(22), // ,, reduce: GARGS
			nil,        // minutes
			reduce(22), // tok_hex, reduce: GARGS
			nil,        // created
			nil,        // by
			reduce(22), // ..., reduce: GARGS
			reduce(22), // _, reduce: GARGS
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(12), // ␚, reduce: GStack
			nil,        // empty
			reduce(12), // tok_enter, reduce: GStack
			reduce(12), // goroutine, reduce: GStack
			nil,        // tok_int
			nil,        // [
			nil,        // ]:
			reduce(12), // tok_identifier, reduce: GStack
			nil,        // ,
			nil,        // minutes
			nil,        // tok_hex
			reduce(12), // created, reduce: GStack
			nil,        // by
			nil,        // ...
			nil,        // _
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			shift(45), // tok_identifier
			nil,       // ,
			nil,       // minutes
			nil,       // tok_hex
			nil,       // created
			nil,       // by
			nil,       // ...
			nil,       // _
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(46), // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			nil,       // tok_identifier
			shift(31), // ,
			nil,       // minutes
			shift(32), // tok_hex
			nil,       // created
			nil,       // by
			shift(33), // ...
			shift(34), // _
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // tok_enter
			nil,        // goroutine
			nil,        // tok_int
			nil,        // [
			nil,        // ]:
			reduce(15), // tok_identifier, reduce: GFuncCall
			nil,        // ,
			nil,        // minutes
			nil,        // tok_hex
			nil,        // created
			nil,        // by
			nil,        // ...
			nil,        // _
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(18), // tok_enter, reduce: GARGS
			nil,        // goroutine
			nil,        // tok_int
			nil,        // [
			nil,        // ]:
			nil,        // tok_identifier
			reduce(18), // ,, reduce: GARGS
			nil,        // minutes
			reduce(18), // tok_hex, reduce: GARGS
			nil,        // created
			nil,        // by
			reduce(18), // ..., reduce: GARGS
			reduce(18), // _, reduce: GARGS
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // tok_enter
			nil,        // goroutine
			nil,        // tok_int
			nil,        // [
			nil,        // ]:
			reduce(17), // tok_identifier, reduce: GFuncCall
			nil,        // ,
			nil,        // minutes
			nil,        // tok_hex
			nil,        // created
			nil,        // by
			nil,        // ...
			nil,        // _
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(48), // tok_enter
			nil,       // goroutine
			nil,       // tok_int
			nil,       // [
			nil,       // ]:
			nil,       // tok_identifier
			shift(31), // ,
			nil,       // minutes
			shift(32), // tok_hex
			nil,       // created
			nil,       // by
			shift(33), // ...
			shift(34), // _
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // tok_enter
			nil,        // goroutine
			nil,        // tok_int
			nil,        // [
			nil,        // ]:
			reduce(16), // tok_identifier, reduce: GFuncCall
			nil,        // ,
			nil,        // minutes
			nil,        // tok_hex
			nil,        // created
			nil,        // by
			nil,        // ...
			nil,        // _
		},
	},
}
