// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 9

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Start
		2,  // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Start
		-1, // Goroutines
		3,  // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Start
		-1, // Goroutines
		6,  // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		9,  // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		17, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		21, // GStack
		22, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		26, // GARGS
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		38, // GARGS
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S33
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S34
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S35
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S36
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S37
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		43, // GARGS
	},
	gotoRow{ // S38
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S39
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S40
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S41
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S42
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S43
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S44
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S45
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		47, // GARGS
	},
	gotoRow{ // S46
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S47
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
	gotoRow{ // S48
		-1, // S'
		-1, // Start
		-1, // Goroutines
		-1, // Goroutine
		-1, // GStatus
		-1, // GStacks
		-1, // GStack
		-1, // GFuncCall
		-1, // GARGS
	},
}
