// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"os"
	"unicode/utf8"

	"github.com/aggronmagi/gstacks/stacks/token"
)

const (
	NoState    = -1
	NumStates  = 52
	NumSymbols = 64
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := os.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '0'
1: 'x'
2: '+'
3: '0'
4: 'x'
5: '\n'
6: 'g'
7: 'o'
8: 'r'
9: 'o'
10: 'u'
11: 't'
12: 'i'
13: 'n'
14: 'e'
15: '['
16: ']'
17: ':'
18: ','
19: 'm'
20: 'i'
21: 'n'
22: 'u'
23: 't'
24: 'e'
25: 's'
26: 'c'
27: 'r'
28: 'e'
29: 'a'
30: 't'
31: 'e'
32: 'd'
33: 'b'
34: 'y'
35: '.'
36: '.'
37: '.'
38: '_'
39: '+'
40: '-'
41: '?'
42: '_'
43: '/'
44: '.'
45: '*'
46: ':'
47: '@'
48: '-'
49: '%'
50: '!'
51: ' '
52: '\t'
53: '\r'
54: '('
55: ')'
56: '{'
57: '}'
58: '0'-'9'
59: 'a'-'f'
60: 'A'-'F'
61: 'a'-'z'
62: 'A'-'Z'
63: .
*/
